# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 430b228e0483cd7569c0ec60d2289c556b3e497308bee5167e7c78c5a646b32815ace6bf83efc92386dd49bc424c128053bfcf845f4b762d5db8003a7119e4b0

test:
  secret_key_base: 682bd320bfc7681fd29da1aec5ffe19a43dc336e92d6f0f8a50cd9e4e63907002d97300777db13829bb9462ff055534f6b43ad660fd1318cea4737b04a8b021b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
